#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("AbsoluteLayout.Resource", IsApplication=true)]

namespace AbsoluteLayout
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int theme_devicedefault_background = 2131099648;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int colombia = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int fondo = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int mexico = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080004
			public const int btncalcular = 2131230724;
			
			// aapt resource value: 0x7f080007
			public const int btnsalir = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int imagencol = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int imagenmex = 2131230729;
			
			// aapt resource value: 0x7f080006
			public const int txtcapitalC = 2131230726;
			
			// aapt resource value: 0x7f080005
			public const int txtcapitalM = 2131230725;
			
			// aapt resource value: 0x7f080003
			public const int txtegresosC = 2131230723;
			
			// aapt resource value: 0x7f080001
			public const int txtegresosM = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int txtingresosC = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int txtingresosM = 2131230720;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int VistaCapital = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_Custom = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
