// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace AccesoSQLiteyServicio.ServicioWindows {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback InsertarenSQLServerOperationCompleted;
        
        /// CodeRemarks
        public Service() {
            this.Url = "http://172.16.73.142/Service.asmx";
        }
        
        public Service(string url) {
            this.Url = url;
        }
        
        /// CodeRemarks
        public event InsertarenSQLServerCompletedEventHandler InsertarenSQLServerCompleted;
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertarenSQLServer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool InsertarenSQLServer(double IngresosMexico, double EgresosMexico, double IngresosColombia, double EgresosColombia) {
            object[] results = this.Invoke("InsertarenSQLServer", new object[] {
                        IngresosMexico,
                        EgresosMexico,
                        IngresosColombia,
                        EgresosColombia});
            return ((bool)(results[0]));
        }
        
        /// CodeRemarks
        public void InsertarenSQLServerAsync(double IngresosMexico, double EgresosMexico, double IngresosColombia, double EgresosColombia) {
            this.InsertarenSQLServerAsync(IngresosMexico, EgresosMexico, IngresosColombia, EgresosColombia, null);
        }
        
        /// CodeRemarks
        public void InsertarenSQLServerAsync(double IngresosMexico, double EgresosMexico, double IngresosColombia, double EgresosColombia, object userState) {
            if ((this.InsertarenSQLServerOperationCompleted == null)) {
                this.InsertarenSQLServerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertarenSQLServerOperationCompleted);
            }
            this.InvokeAsync("InsertarenSQLServer", new object[] {
                        IngresosMexico,
                        EgresosMexico,
                        IngresosColombia,
                        EgresosColombia}, this.InsertarenSQLServerOperationCompleted, userState);
        }
        
        private void OnInsertarenSQLServerOperationCompleted(object arg) {
            if ((this.InsertarenSQLServerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertarenSQLServerCompleted(this, new InsertarenSQLServerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void InsertarenSQLServerCompletedEventHandler(object sender, InsertarenSQLServerCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertarenSQLServerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertarenSQLServerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}
