// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace AccesoSQLiteyServicio.ServicioLinux {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicioWEBSoap", Namespace="http://tempuri.org/")]
    public partial class ServicioWEB : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback InsertarenMySQLServerOperationCompleted;
        
        /// CodeRemarks
        public ServicioWEB() {
            this.Url = "http://192.168.2.153/ServicioWEB.asmx";
        }
        
        public ServicioWEB(string url) {
            this.Url = url;
        }
        
        /// CodeRemarks
        public event InsertarenMySQLServerCompletedEventHandler InsertarenMySQLServerCompleted;
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertarenMySQLServer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool InsertarenMySQLServer(double IngresosMexico, double EgresosMexico, double IngresosColombia, double EgresosColombia) {
            object[] results = this.Invoke("InsertarenMySQLServer", new object[] {
                        IngresosMexico,
                        EgresosMexico,
                        IngresosColombia,
                        EgresosColombia});
            return ((bool)(results[0]));
        }
        
        /// CodeRemarks
        public void InsertarenMySQLServerAsync(double IngresosMexico, double EgresosMexico, double IngresosColombia, double EgresosColombia) {
            this.InsertarenMySQLServerAsync(IngresosMexico, EgresosMexico, IngresosColombia, EgresosColombia, null);
        }
        
        /// CodeRemarks
        public void InsertarenMySQLServerAsync(double IngresosMexico, double EgresosMexico, double IngresosColombia, double EgresosColombia, object userState) {
            if ((this.InsertarenMySQLServerOperationCompleted == null)) {
                this.InsertarenMySQLServerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertarenMySQLServerOperationCompleted);
            }
            this.InvokeAsync("InsertarenMySQLServer", new object[] {
                        IngresosMexico,
                        EgresosMexico,
                        IngresosColombia,
                        EgresosColombia}, this.InsertarenMySQLServerOperationCompleted, userState);
        }
        
        private void OnInsertarenMySQLServerOperationCompleted(object arg) {
            if ((this.InsertarenMySQLServerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertarenMySQLServerCompleted(this, new InsertarenMySQLServerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void InsertarenMySQLServerCompletedEventHandler(object sender, InsertarenMySQLServerCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertarenMySQLServerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertarenMySQLServerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}
